frontend/urls.py
from .views import *
from django.urls import path

app_name = "frontend"

urlpatterns = [
    path('', index, name="index"),
    path('matriculas', matriculas, name="matriculas"),
    path('nueva_matricula/', nueva_matricula, name="nueva_matricula"),
]

oxford/oxford/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

oxford/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
]

backend/models.py
import statistics

from django.db import models
from django.db.models import Sum
from django.forms import model_to_dict
from datetime import timedelta, datetime


class Base(models.Model):
    name = models.CharField(max_length=125, verbose_name="nombre")
    is_active = models.BooleanField(default=True, verbose_name="activo")

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

    def to_json(self):
        try:
            return model_to_dict(self)
        except (KeyError, ValueError):
            return {}


class Person(models.Model):
    first_name = models.CharField(max_length=125, verbose_name="nombres")
    last_name = models.CharField(max_length=125, verbose_name="apellidos")
    number_id = models.CharField(max_length=14, verbose_name="número de cédula")
    address = models.TextField(max_length=255, verbose_name="dirección")
    phone_number = models.CharField(max_length=8, verbose_name="número de teléfono")
    date_of_bird = models.DateField(verbose_name="fecha de nacimiento", null=False, blank=False)

    class Meta:
        abstract = True

    def __str__(self):
        return " ".join([self.first_name, self.last_name])

    @property
    def age(self):
        return round((datetime.now() - datetime(year=self.date_of_bird.year, month=self.date_of_bird.month,
                                                day=self.date_of_bird.day)).days / 356, 0)

    @classmethod
    def statistics(cls):
        data = [x.age for x in cls.objects.all()]
        return statistics.median(data), statistics.mode(data)

    @classmethod
    def moda(cls):
        data = [x.age for x in cls.objects.all()]
        return statistics.mode(data)

    @classmethod
    def moda(cls):
        data = [x.age for x in cls.objects.all()]
        return statistics.mode(data)


class Building(Base):

    @property
    def total_classrooms(self):
        return ClassRoom.objects.filter(floor__in=Floor.objects.filter(building=self)).count()

    total_classrooms.fget.short_description = "Total de salones"

    class Meta:
        verbose_name = "edificio"


class Floor(Base):
    building = models.ForeignKey(Building, on_delete=models.CASCADE, related_name='floors', verbose_name="edificio")

    class Meta:
        verbose_name = "piso"


class ClassRoom(Base):
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE, verbose_name='número de piso',
                              related_name="classrooms_by_floor", null=True)

    class Meta:
        verbose_name = "salon"
        verbose_name_plural = "salones"


class Shift(Base):
    class Meta:
        verbose_name = "turno"


class ProfessorType(Base):
    class Meta:
        verbose_name = "tipo de profesór"
        verbose_name_plural = "tipos de profesóres"


class Professor(Person):
    professor_type = models.ForeignKey(ProfessorType, on_delete=models.PROTECT, verbose_name="tipo de profesór")

    class Meta:
        verbose_name = "profesor"
        verbose_name_plural = "profesores"


class Student(Person):
    class Meta:
        verbose_name = "estudiante"


class Program(Base):
    class Meta:
        verbose_name = 'programa'

    @property
    def duration(self):
        return timedelta(weeks=self.course_set.all().aggregate(Sum('weeks'))['weeks__sum'] or 0).days / 365

    @property
    def full_cost(self):
        return self.course_set.all().aggregate(Sum('cost'))['cost__sum'] or 0.0


class Course(Base):
    program = models.ForeignKey(Program, on_delete=models.PROTECT, verbose_name="programa")
    professor = models.ForeignKey(Professor, on_delete=models.PROTECT, verbose_name="Profesor",
                                  null=True)
    cost = models.FloatField(default=0.0, verbose_name="precio del curso")
    credit = models.IntegerField(default=0, verbose_name="creditos del curso")
    grade = models.IntegerField(default=0, verbose_name="notas del curso")
    weeks = models.PositiveSmallIntegerField(default=5, verbose_name="duracción en semanas del curso")

    class Meta:
        verbose_name = "curso"

    def to_json(self):
        o = super().to_json()
        if self.id:
            o['professor'] = str(self.professor)
        return o


class Enrollment(Base):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name="estudiante")
    program = models.ForeignKey(Program, on_delete=models.CASCADE, verbose_name="carrera")


class Grades(Base):
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE, verbose_name="matricula")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="curso", null=True)
    grade = models.IntegerField(default=0, verbose_name="nota")


def _statistics(cls, field):
    a, b, c, d, e = 0, 0, 0, 0, 0
    data = [getattr(cls, field, 0) for x in cls.objects.all()]
    try:
        a = statistics.median(data)
    except TypeError:
        pass
    try:
        b = statistics.mode(data)
    except TypeError:
        pass
    try:
        c = statistics.mean(data)
    except TypeError:
        pass
    try:
        d = min(data)
    except TypeError:
        pass
    try:
        e = max(data)
    except TypeError:
        pass

    return a, b, c, d, e

frontend/forms.py
from backend.models import *
from django import forms
from .widgets import *


class MatriculaForm(forms.ModelForm):
    program = forms.ModelChoiceField(queryset=Program.objects.all(), label="Programa de estudios/Carrera")
    courses = forms.Field(label="Cursos incluidos en el programa", required=False,
                          widget=CoursesWidget)

    class Meta:
        model = Student
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['courses'].widget.attrs['choices'] = Course.objects.all()

frontend/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import JsonResponse
from .forms import *
from django.urls import reverse
from backend.models import _statistics


def index(request):
    return render(request, 'frontend/index.html', {
        'programs': Program.objects.all(),
        'students': Student.objects.all(),
        'statistics_student': _statistics(Course, 'credit'),
        'statistics_course': _statistics(Course, 'credit'),
    })


def matriculas(request):
    return render(request, 'frontend/matriculas.html', {
        'matriculas': Student.objects.all(),
    })


def nueva_matricula(request):
    form = MatriculaForm
    if request.method == "POST":
        if 'get_courses' in request.POST:
            return JsonResponse([x.to_json() for x in Course.objects.filter(program_id=request.POST.get('program'))],
                                safe=False)
        form = form(request.POST)
        if form.is_valid():
            estudiante = form.save()
            matricula = Enrollment(student=estudiante, program_id=request.POST.get('program'))
            matricula.save()
            courses = request.POST.getlist('courses')
            for course in courses:
                Grades(enrollment=matricula, course_id=course).save()
            return HttpResponseRedirect(reverse('frontend:matriculas'))
    return render(request, 'frontend/nueva-matricula.html', {
        'form': form,
    })

frontend/templates/frontend/index.html
<!doctype html>
{% load humanize %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Universidad de Oxford</title>

    {% block style %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
              integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
              crossorigin="anonymous">
    {% endblock %}

</head>
<body>
{% block navbar %}
    <nav id="navbar-example2" class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Universidad de Oxford</a>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'frontend:index' %}">Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'frontend:matriculas' %}">Matriculas</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                   aria-expanded="false">{% if user.is_authenticated %}{{ user.get_full_name }}
                {% else %}Ingresa{% endif %}</a>

                {% if user.is_authenticated %}
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Administracion</a>
                        <div role="separator" class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'admin:logout' %}">Salir</a>
                    </div>
                {% else %}
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Crea una cuenta</a>
                    </div>
                {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}

{% block  breadcrumb %}{% endblock %}

{% block content %}

    <div class="jumbotron">
        <h1 class="display-4">Bienvenido!</h1>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus accusantium aut autem
            consequuntur delectus dignissimos dolor, illum ipsam iusto maiores nemo, nesciunt nulla praesentium
            repudiandae sequi sint veritatis vero.</p>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Programas disponibles</th>
                        <th>Costo total del programa</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for program in programs %}
                        <tr>
                            <td>{{ program }}</td>
                            <td>{{ program.full_cost }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th colspan="2">
                            Estadisticas
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Edad de estudiantes</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Notas de estudiantes</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Edad de los profesores</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Los creditos ganados por los estudiantes</td>
                        <td>{{ statistics_student.0 }}</td>
                        {#                        <td>{{ statistics_student.1 }}</td>#}
                        <td>{{ statistics_student.2 }}</td>
                        <td>{{ statistics_student.3 }}</td>
                        <td>{{ statistics_student.4 }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
            integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
            crossorigin="anonymous"></script>
{% endblock %}

</body>
</html>

frontend/templates/frontend/matriculas.html
{% extends 'frontend/index.html' %}
{% load crispy_forms_filters %}

{% block  breadcrumb %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'frontend:index' %}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="#">Matriculas</a></li>
            {#            <li class="breadcrumb-item active" aria-current="page">Data</li>#}
        </ol>
    </nav>

{% endblock %}


{% block content %}
    <div class="container">
        <h1 style="display: flex; justify-content: center; align-items: center">Matriculas</h1>
        <div class="row" style="margin: 10px 0;">
            <div class="col-md-8">
                <input type="text" placeholder="Buscar" class="form-control"
                style="width: 100%">
            </div>
            <div class="col-md-4">
                <a href="{% url 'frontend:nueva_matricula' %}" class="btn btn-info float-right">Nueva matrícula</a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Identificación</th>
                    <th>Número de teléfono</th>
                    <th>Fecha de nacimiento</th>
                </tr>
                </thead>
                <tbody>
                {% for matricula in matriculas %}
                    <tr>
                        <td>{{ matricula.first_name }}</td>
                        <td>{{ matricula.last_name }}</td>
                        <td>{{ matricula.number_id }}</td>
                        <td>{{ matricula.phone_number }}</td>
                        <td>{{ matricula.date_of_bird }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

frontend/templates/frontend/nueva-matricula.html
{% extends 'frontend/index.html' %}
{% load crispy_forms_filters %}

{% block style %}
    {{ block.super }}
    <style type="text/css">
        tr.active {
            background-color: yellow;
        }
        .numeric{
            text-align: right;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form action="." method="post" novalidate>
                    {% csrf_token %}
                    <fieldset>
                        <div class="row">
                            <div class="col">{{ form.first_name|as_crispy_field }}</div>
                            <div class="col">{{ form.last_name|as_crispy_field }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form.number_id|as_crispy_field }}</div>
                            <div class="col">{{ form.phone_number|as_crispy_field }}</div>
                            <div class="col">{{ form.date_of_bird|as_crispy_field }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form.address|as_crispy_field }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form.program|as_crispy_field }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form.courses|as_crispy_field }}</div>
                        </div>
                    </fieldset>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">

      $(document).ready(function () {

        $(document).on('change', '#id_program', function () {
          const _this = $(this);
          const token = $('input[name="csrfmiddlewaretoken"]').val();
          console.log(_this, token);
          $.ajax('.', {
            method: "post",
            data: {
              get_courses: 'get_courses',
              program: _this.val(),
              csrfmiddlewaretoken: token,
            },
            success: function (response) {
              const $courses = $('#table-courses').empty();
              $.each(response, function (i, o) {
                $courses.append(`<tr>
                        <td>
                            <input type="checkbox" class="select-course">
                            <input type="hidden" value=${o.id} class="course-container">
                        </td>
                        <td>${o.name}</td>
                        <td>${o.professor}</td>
                        <td class="numeric weeks">${o.weeks}</td>
                        <td class="numeric cost">${o.cost}</td>
                    </tr>`);
              })
            }
          });
        });


        $(document).on('change', '.select-course', function () {
          const _this = $(this);
          const $tr = _this.parents('tr');
          if (_this.is(':checked')) {
            $tr.addClass('active');
            $tr.find('.course-container').attr('name', 'course');
          } else {
            $tr.removeClass('active');
            $tr.find('.course-container').removeAttr('name');
          }
          const table = $('#table-courses tr.active');
          let total = 0;
          let duration = 0;
          $.each(table, function (i, tr) {
            total += parseFloat($(tr).find('.cost').html());
            duration += parseFloat($(tr).find('.weeks').html());
          })
          $('#total-cost').val(total);
          $('#total-weeks').val(duration);
        })

      })
    </script>
{% endblock %}

frontend/templates/frontend/widgets/course.html
<table class="table">
    <thead>
    <tr>
        <th></th>
        <th>Curso</th>
        <th>Profesor</th>
        <th class="numeric">Duracion (semanas)</th>
        <th class="numeric">Precio</th>
    </tr>
    </thead>
    <tbody id="table-{{ widget.name }}">
    {% for choise in widget.attrs.choises %}
        <tr>
            <td><input type="checkbox"><input type="hidden" name="course" value="{{ choise.id }}"></td>
            <td>{{ choise.name }}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th>Totales</th>
            <th></th>
            <th>-</th>
            <th class="numeric"><input type="text" readonly  id="total-weeks" class="numeric"></th>
            <th class="numeric"><input type="text" readonly id="total-cost" class="numeric"></th>
        </tr>
    </tfoot>
</table>